#!/bin/bash
# Author: xuyijun

mysqlu='root'
mysqlp=''
mysqlh='127.0.0.1'
db=''

unamestr=`uname`
# 判断环境为 macOS，可作为开发环境，设置不同配置
if [[ "$unamestr" == 'Darwin' ]]; then
    mysqlu='root'
    mysqlp=''
    mysqlh='127.0.0.1'
    db="sakila"
fi

#执行条件分支标识
flag=0

# ref: https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
# https://www.ibm.com/developerworks/cn/linux/l-bash-test.htm
if [[ "$#" -eq 1 && $1 -ge 1 && $1 -le 10 ]]; then
    # echo $1
    flag=$1
else
    echo "未设置 flag 参数，或参数不符合，使用默认查询条件。"
fi

if [[ $flag == "2" ]]; then
    sql="select film_id,title,rental_rate from film order by rental_rate desc limit 10"
    echo "查询条件2：正在获取..数据表 film 中 rental_rate 最高的 10 条记录："
else
    sql="select count(0) from film;"
    echo "查询条件1：正在获取..数据表 film 的记录数量："
fi

# ref: https://www.shellhacks.com/mysql-run-query-bash-script-linux-command-line/
sleep 1s;
# mysql "$db" -u $mysqlu -p$mysqlp -h$mysqlh -e "$sql"
mysql "$db" -u $mysqlu -h$mysqlh -e "$sql"

exit 0
